### ISSUE TITLE
Compatibility of Package

### ISSUE THREAD

**Issue by Chen-X666** [SHUMKASHUN/Automate-CoT#1]
Hi, Could u provide the requirement.txt to aviod the error in compatibility of package

**Comment by Chen-X666** [comment]
Could u provide the dataset after processing as well, many thanks

**Comment by SHUMKASHUN** [comment]
Hi, sorry for the late reply. I cannot find the exact original environment now. But I think most packages are in standard version except openai package should be old ~0.26 - 0.28. Could you share your problem on compatibility of package so that I may take a look for you?

**Comment by SHUMKASHUN** [comment]
I have also uploaded the gsm8k preprocess script for your reference. Other datasets are  using the same script by just changing the index number and column name.
