### ISSUE TITLE
Cannot import name 'load_dataset' from 'datasets'

### ISSUE THREAD

**Issue by xioahua** [SHUMKASHUN/Automate-CoT#2]
Hi, Could you provide the load_dataset method? thanks

**Comment by SHUMKASHUN** [comment]
Hi, load_dataset is a method from datasets package from Huggingface (https://pypi.org/project/datasets/), you can install it via pip. It now has version 3.x, you may have a try with 2.x as that is the version when we are doing the experiments.

**Comment by SHUMKASHUN** [comment]
@xioahua , if you still have questions, you can @ me so that I can easily see your message. Thanks!
